server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/product_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate # let flyway handle schema
    show-sql: true


  flyway:
    locations:
      - classpath:db/migration
      - classpath:db/migration/category
    enabled: true
    baseline-on-migrate: true

# Any custom config
product:
  service:
    greeting: "Hello from Product Service!"