server:
  port: ${APP_PORT:8082}

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate # let flyway handle schema
    show-sql: true


  flyway:
    locations:
      - classpath:db/migration
      - classpath:db/migration/category
    enabled: true
    baseline-on-migrate: true

# Any custom config
product:
  service:
    greeting: ${MSG:DEFAULT MESSAGE IF NOT SET}